# Generated by Django 3.2.1 on 2022-05-10 09:29

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('bus_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bus_number', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=100)),
                ('seats', models.FloatField(default=0, max_length=5)),
                ('cost_per_seat', models.IntegerField()),
                ('departure_point', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2)),
                ('depart_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
