# Generated by Django 4.0.4 on 2022-04-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='arrival_point',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='destination',
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='driver.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='driver.location'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
