# Generated by Django 4.0.4 on 2022-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_bus_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
