# Generated by Django 4.0.4 on 2022-05-06 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_bus_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='bus',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='depart',
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Vehicle_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('routes', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], max_length=2)),
                ('vehicle_status', models.CharField(choices=[('1', 'Fully Serviced'), ('2', 'Service Pending')], max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='driver.bus')),
            ],
        ),
    ]
