# Generated by Django 3.2.1 on 2022-05-09 12:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_rename_bus_schedule_vehicle_remove_bus_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_image',
            field=cloudinary.models.CloudinaryField(default='image1', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
