# Generated by Django 4.0.4 on 2022-05-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_rename_bus_schedule_vehicle_remove_bus_depart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_owner',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.bus'),
        ),
    ]
