# Generated by Django 3.2.1 on 2022-05-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(default=-446)),
                ('departure_point', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('time', models.TimeField()),
                ('no_of_seats', models.IntegerField(default=0)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_id', to='driver.bus')),
            ],
        ),
    ]
