# Generated by Django 4.0.4 on 2022-05-05 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0004_alter_bus_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(default=-446)),
                ('user_id', models.IntegerField(default=0)),
                ('departure_point', models.CharField(max_length=100)),
                ('pick_up_station', models.CharField(default='Home station', max_length=100)),
                ('destination', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('time', models.TimeField()),
                ('no_of_seats', models.IntegerField(default=0)),
                ('bus_name', models.CharField(max_length=20)),
                ('bus_id', models.IntegerField()),
                ('seat_numbers', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('seats', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.schedule')),
            ],
        ),
    ]
