# Generated by Django 4.0.4 on 2022-05-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_bus_seats'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='bus_name',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='pick_up_station',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='seat_numbers',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='bus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_id', to='driver.bus'),
        ),
    ]
